### PR TITLE
Render openapi

### PR DESCRIPTION
**Pull request by lognaturel**
Small changes related to integrating Central API docs.

@sadiqkhoja you could cherry-pick specific commits you like or if you are ok with them all, rebase and merge.

Some things left to investigate, likely as follow-up work. I'll write the list here so @sadiqkhoja can decide whether any should be handled before an initial merge.

- [ ] The output when extended metadata can be requested is really confusing. It looks like the example is always the extended one. And then the schema shows two arrays with no indication of what they mean. I think ideally they would be shown as two separate example/schema pairs, like in Apiary previously. I think the issue might be in the conversion to OpenAPI. I also no
- [ ] It would be nice to style text surrounded by backticks in parameter tables (``code``)
- [ ] Build some light tooling to manage multiple versions and allow users to navigate between them.
- [ ] Run tests in CI

From my perspective, we could merge once the changes in this PR are made. It will be a bit confusing to have active API docs in two places but I think it would be good to publish these pages and share them with the team and other power users before pulling down the Apiary ones.

### CODE REVIEW

**Comment by lognaturel** [comment]
Not saying we should change this now but did you consider building markdown files instead of building RST pages with embedded HTML (using https://www.sphinx-doc.org/en/master/usage/markdown.html)?

**Comment by sadiqkhoja** [comment]
Yes but quite late in the process :(

Even then I wasn't sure if I can use all the components in markdown that we have in our documentation like tables, tabs and collapsibles

**Review by sadiqkhoja — APPROVED** [review]
it was so easy to review this PR because of the small and well defined commits

**Comment by sadiqkhoja** [comment]
I would like to work on the above list after initial merge

**Comment by lognaturel** [comment]
> Yes but quite late in the process :(

No worries, I'm not convinced it would be better, I just wanted a sense of whether you had tried and abandoned it vs not considered it initially. That could be useful info in the future if we find ourselves needing to rework some of it.

Can you rebase and merge onto your branch? I don't have committer access to your fork. 😊 Then that should put me in a good place to do final review on the PR targeting the real repo.

**Pull request merged**
